import{a as L,S as w,i as l}from"./assets/vendor-b11e2a50.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&r(d)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const S="45301554-42ab9bd7e2b914874aa400849",v="https://pixabay.com/api/";async function p(s,t,i){const r=new URLSearchParams({key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:t,page:i});try{return(await L.get(`${v}?${r}`)).data}catch(e){return console.error(e),{hits:[],totalHits:0}}}function y(s){const t=document.querySelector(".gallery"),i=s.map(r=>`<a class="gallery-item" href="${r.largeImageURL}">
        <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" title="${r.tags}" width="360" />
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${r.likes}</p>
          <p class="info-item"><b>Views:</b> ${r.views}</p>
          <p class="info-item"><b>Comments:</b> ${r.comments}</p>
          <p class="info-item"><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </a>`).join("");t.insertAdjacentHTML("beforeend",i)}const m=document.querySelector(".search-form"),P=document.querySelector(".gallery"),c=document.querySelector(".loader"),f=document.querySelector(".load-more-button");let h=new w(".gallery a"),a=1;const g=15;let n="",u=0,b=0;m.addEventListener("submit",async s=>{if(s.preventDefault(),n=m.querySelector(".search-input").value.trim(),n!==""){P.innerHTML="",a=1,c.classList.remove("is-hidden"),f.classList.add("is-hidden");try{const t=await p(n,g,a),i=t.hits;u=t.totalHits,b=Math.ceil(u/g),u===0?l.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",titleColor:"#fff",messageColor:"#fff",color:"#ef4040",icon:null}):(y(i),h.refresh(),a+=1,f.classList.remove("is-hidden"))}catch(t){console.error(t),l.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",titleColor:"#fff",messageColor:"#fff",color:"#ef4040",icon:null})}finally{m.reset(),c.classList.add("is-hidden")}}});f.addEventListener("click",async()=>{a>=b&&(f.classList.add("is-hidden"),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"bottomRight",titleColor:"#fff",messageColor:"#fff",color:"#2196F3",icon:null})),c.classList.remove("is-hidden");try{const t=(await p(n,g,a)).hits;y(t),h.refresh(),a+=1;const{height:i}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}catch(s){console.error(s),l.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",titleColor:"#fff",messageColor:"#fff",color:"#ef4040",icon:null})}finally{c.classList.add("is-hidden")}});
//# sourceMappingURL=commonHelpers.js.map
